/*
 * SelKMLData.java
 *
 * Created on 18 de agosto de 2008, 02:39 PM
 */

package imm.gis.core.gui;

import imm.gis.core.controller.ContAccionesAplicacion;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
//import java.io.File;
import java.util.ArrayList;
import java.util.HashMap;
//import java.util.Iterator;
//import java.util.Set;

import javax.swing.JComponent;
//import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JRootPane;
import javax.swing.KeyStroke;
//import javax.swing.filechooser.FileFilter;

/**
 *
 * @author  imm
 */
public class SelKMLData extends javax.swing.JDialog {

	private static final long serialVersionUID = 1L;
//	private static HashMap<String,ArrayList<String>> combos;
//	private static ContAccionesAplicacion cont = null;
	
	private ActionListener closeListener;

    /** Creates new form SelKMLData */
    public SelKMLData(JFrame parent, boolean modal,ContAccionesAplicacion caa, HashMap<String,ArrayList<String>> cmbs) {
        super(parent,"Datos del archivo kml",modal);
		setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
 //       combos = cmbs;
 //       cont = caa;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {
/*
    	setResizable(false);
    	lab_capa = new javax.swing.JLabel();
        cmb_capa = new javax.swing.JComboBox();
        
        Set<String> layers = combos.keySet();
        Iterator<String> iter = layers.iterator();
        cmb_capa.addItem("");
        while (iter.hasNext())
        	cmb_capa.addItem(iter.next());

        jLabel2 = new javax.swing.JLabel();
        cmb_etiqueta = new javax.swing.JComboBox();
        cmb_etiqueta.setEnabled(false);
        
        jPanel1 = new javax.swing.JPanel();
        txt_ruta = new javax.swing.JTextField();
        txt_ruta.setEnabled(false);
        txt_ruta.setEditable(false);
        
        but_examinar = new javax.swing.JButton();
        but_examinar.setEnabled(false);
        but_aceptar = new javax.swing.JButton();
        but_aceptar.setEnabled(false);
        but_cancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lab_capa.setText("Capa");

        jLabel2.setText("Etiqueta");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Carpeta de destino", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 0, 0))); // NOI18N

        but_examinar.setText("Examinar...");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_ruta, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(but_examinar, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_ruta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(but_examinar))
                .addGap(27, 27, 27))
        );

        but_aceptar.setText("Aceptar");

        but_cancelar.setText("Cancelar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 509, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(lab_capa, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmb_capa, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmb_etiqueta, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(but_aceptar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(but_cancelar)
                        .addGap(51, 51, 51))))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(19, 19, 19)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lab_capa)
                        .addComponent(cmb_capa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cmb_etiqueta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2))
                    .addGap(18, 18, 18)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(but_cancelar)
                        .addComponent(but_aceptar))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );

        cmb_capa.addActionListener(new ActionListener(){

			public void actionPerformed(ActionEvent e) {
				txt_ruta.setText("");
				if (cmb_capa.getSelectedIndex()==0){
					cmb_etiqueta.setEnabled(false); 
					txt_ruta.setEnabled(false); 
					but_examinar.setEnabled(false);
					but_aceptar.setEnabled(false);
				}
				else{
					cmb_etiqueta.setEnabled(true);
					cmb_etiqueta.removeAllItems();
			        Iterator<String> iter = combos.get(cmb_capa.getSelectedItem()).iterator();
			        cmb_etiqueta.addItem("ID POR DEFECTO");
			        while (iter.hasNext())
			        	cmb_etiqueta.addItem(iter.next());
				}
			}
        	
        });

        cmb_etiqueta.addActionListener(new ActionListener(){

			public void actionPerformed(ActionEvent e) {
					txt_ruta.setEnabled(true); 
					but_examinar.setEnabled(true);
			}
        	
        });
        
        but_examinar.addActionListener(new ActionListener(){

			public void actionPerformed(ActionEvent e) {
				JFileChooser fc = new JFileChooser("C:\\Documents and Settings\\imm\\Escritorio\\kmls");
				
				FileFilter kmlFileFilter = new FileFilter(){
					public boolean accept(File f){
						return f.isDirectory();
					}
					
					public String getDescription(){
						return "Todas las carpetas";
					}
				};
				
				fc.setAcceptAllFileFilterUsed(false);
				fc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
				fc.addChoosableFileFilter(kmlFileFilter);

				int res = fc.showSaveDialog(null);
				if (res == JFileChooser.APPROVE_OPTION){
					txt_ruta.setText(fc.getSelectedFile().getAbsolutePath() + 
							System.getProperty("file.separator") + 
							cmb_capa.getSelectedItem().toString().replace(" ","_") + ".kml");
					but_aceptar.setEnabled(true);
				}
			}
        	
        });
        
        but_aceptar.addActionListener(new ActionListener(){
			public void actionPerformed(ActionEvent e) {
				cont.pgsql2kml(txt_ruta.getText(),
							   cmb_capa.getSelectedItem().toString(),
							   cmb_etiqueta.getSelectedItem().toString());
				dispose();
			}
		});
        
        but_cancelar.addActionListener(new ActionListener(){
			public void actionPerformed(ActionEvent e) {
					dispose();
			}
		});
        
        closeListener = new ActionListener() {
        	public void actionPerformed(ActionEvent actionEvent) {
        		setVisible(false);
        	}
        };

        pack();
        */
    }// </editor-fold>

	protected JRootPane createRootPane() {
		KeyStroke stroke = KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0);
		JRootPane rootPane = new JRootPane();

		rootPane.registerKeyboardAction(new ActionListener(){
					public void actionPerformed(ActionEvent e){
						closeListener.actionPerformed(new ActionEvent(this, ActionEvent.ACTION_PERFORMED, ""));
					}
				}, 
				stroke,
				JComponent.WHEN_IN_FOCUSED_WINDOW);

		return rootPane;
	}
	
    // Variables declaration - do not modify
//    private javax.swing.JButton but_aceptar;
//    private javax.swing.JButton but_cancelar;
//    private javax.swing.JButton but_examinar;
//    private javax.swing.JComboBox cmb_capa;
//    private javax.swing.JComboBox cmb_etiqueta;
//    private javax.swing.JLabel jLabel2;
//    private javax.swing.JPanel jPanel1;
//    private javax.swing.JLabel lab_capa;
//    private javax.swing.JTextField txt_ruta;
    // End of variables declaration

}
